"""add created_at columns

Revision ID: 3a420b7b1457
Revises: 49d449f04483
Create Date: 2025-08-12 01:43:23.687489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a420b7b1457'
down_revision: Union[str, Sequence[str], None] = '49d449f04483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_request', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('ad_selection', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('ad_variant', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad_variant', 'created_at')
    op.drop_column('ad_selection', 'created_at')
    op.drop_column('ad_request', 'created_at')
    # ### end Alembic commands ###
