"""init tables

Revision ID: 49d449f04483
Revises: 
Create Date: 2025-08-12 01:23:53.143915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d449f04483'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_request',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_request_session_id'), 'ad_request', ['session_id'], unique=False)
    op.create_table('ad_selection',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('variant_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_ad_selection_variant_id'), 'ad_selection', ['variant_id'], unique=False)
    op.create_table('ad_variant',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('index_no', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_variant_request_id'), 'ad_variant', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ad_variant_request_id'), table_name='ad_variant')
    op.drop_table('ad_variant')
    op.drop_index(op.f('ix_ad_selection_variant_id'), table_name='ad_selection')
    op.drop_table('ad_selection')
    op.drop_index(op.f('ix_ad_request_session_id'), table_name='ad_request')
    op.drop_table('ad_request')
    # ### end Alembic commands ###
