"""fix ad_request.id identity

Revision ID: f72b1606a433
Revises: 3a420b7b1457
Create Date: 2025-08-16 12:34:29.677976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f72b1606a433'
down_revision: Union[str, Sequence[str], None] = '3a420b7b1457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from alembic import op

def upgrade():
    op.execute("""
        DO $$
        BEGIN
            BEGIN
                ALTER TABLE ad_request
                ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            EXCEPTION WHEN duplicate_object THEN
                NULL;
            END;
        END $$;
    """)

def downgrade():
    op.execute("ALTER TABLE ad_request ALTER COLUMN id DROP IDENTITY IF EXISTS")